### ISSUE TITLE
Support custom contents of states in StatefulButton 

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1008]
~Let's expose the whole contents of the StatefulButtons~

~We can test if `stateOne` is a React element with https://facebook.github.io/react/docs/react-api.html#isvalidelement and just pass it through if it is, if not we can do what we do now.~

**Comment by tanhengyeow** [comment]
Hi @interactivellama !

I'm guessing the context has changed much since this issue was raised. States are now exposed to the user e.g. [here](https://github.com/salesforce/design-system-react/blob/master/components/button-stateful/__examples__/icon-text.jsx#L25) and an object is passed in as a prop.

Thus I want to clarify if this statement still applies since a React element isn't used anymore:
```
We can test if stateOne is a React element with https://facebook.github.io/react/docs/react-api.html#isvalidelement and just pass it through if it is, if not we can do what we do now.
```

If that's the case, is this issue still valid? Would be glad to do any follow up work :)

**Comment by interactivellama** [comment]
This one of the older components. The way this component's props would work now to align with other components in the library would be to pass in a complete `<Button/>` component into a `defaultButton`, a `selectedButton` and a `deselectButton` and deprecate `stateOne`, `stateTwo`, and `stateThree`.

The top level props would need to still be passed on, but removed the from the public API.

I wouldn't call this one a high priority, but if you'd like to propose completely new props, I'd be open to that as a good initial step for creating a scrum "definition of ready." 

We'd want to not break the old props, but we could do a test on if `stateOne` had a value, and when the old API was detected, it would switch the render to a sub component which would be the current `index.jsx` just renamed `button-stateful/private/deprecated-button-stateful.jsx` or something like that..

**Comment by interactivellama** [comment]
I just reviewed the markup again and we don't want to pass in three full `Button` components. I'm going close this for now. If any consumers discover they need their icons on the right or something like that, please re-open.
