### ISSUE TITLE
Add Vertical Tabs component

### ISSUE THREAD

**Issue by ccotofanasf** [salesforce/design-system-react#1197]
Hello, our team implemented the SLDS vertical tabs component as a react component, since it does not already exist in DSR, and we would like to contribute it back. We will follow the contributing guidelines and add more details when we get a chance. Thank you. 

SLDS component implemented:
https://www.lightningdesignsystem.com/components/vertical-tabs/#content

**Comment by interactivellama** [comment]
Should we use the tabs component and make a variant called "vertical"?

Please note that the file structure changed recently when you pull down master.

**Comment by ccotofanasf** [comment]
What do you mean by "variant"? A prop to control whether it renders horizontally or vertically? Or something else? Thanks.

**Comment by interactivellama** [comment]
Yes "A prop to control whether it renders horizontally or vertically." It seems like the same interface except up and down instead of vertical. 

Although on further reflection of our current codebase, the component should be controlled and selection should be decided by the end developer. Right, now in `Tabs`, there is a fair amount of DOM accessing and keeping selection state uncontrolled (that is selection state within the component that I've talked to a few engineers that had problems preventing tab selection by the use). Let's do a separate component, and we could reconcile (or wrap) in the future if we wanted to. Here's most of the API for horizontal `Tabs`. Does that sound good to you?

```
<VerticalTabs id="tabs-example-default">
  <TabsPanel label="Item One">
    Item One Content
  </TabsPanel>
  <TabsPanel label="Item Two">
    Item Two Content
  </TabsPanel>
  <TabsPanel label="Item Three">
    Item Three Content
  </TabsPanel>
  <TabsPanel disabled label="Disabled">
    Disabled Content
  </TabsPanel>
```
Sorry, for any confusion, since it will be controlled arrow key up/down movement can probably just call an `onRequestSelect` with the next "indexed id" and pass that up to the state container, and then the state container could pass the same tab id/item back into a compare for a `selected` boolean prop on each Tab. That's what I'm thinking for the accessibility part.

**Comment by interactivellama** [comment]
@ccotofanasf Did you want to still want to contribute this component? If you'd like to still contribute as a separate component (separate than Horizontal Tabs) that's OK, too. If you'd like still contribute, please re-open this issue. Thanks!
