### ISSUE TITLE
IE & Edge do not support Object.findIndex()

### ISSUE THREAD

**Issue by nhazar** [salesforce/design-system-react#1221]
https://github.com/salesforce/design-system-react/blob/9bdf2906694c28cb3faafd2f68b5e61a4b367ffe/components/combobox/combobox.jsx#L242
IE & Edge do not support Object.findIndex, you should use lodash's findIndex() instead.

**Comment by interactivellama** [comment]
I think `findIndex` is a ES2015. Should we add something to the readme about Babel Polyfill? We don't really have a browser support matrix, since this library is published in ES6+ and CJS. Is the UMD bundle failing? For the convenience bundle, we do try to target IE. We should probably build the bundle with `babel/polyfill` if we aren't. https://github.com/babel/babel-loader/issues/73

What are your transpiling and polyfill settings?

**Comment by interactivellama** [comment]
There are many `lodash` functions already present. I believe this is do to testing in PhantomJS. We may want to polyfill with that, too.

**Comment by nhazar** [comment]
exactly, `lodash` has a nice polyfill for `findIndex()` that should be used instead.

**Comment by interactivellama** [comment]
Adding for posterity:

Design System React should be treated as source code for your build system. It is not a browser-ready library. The recommended way of consuming this library has ES2017+ language features and therefore cannot be run in the browser without transpiling within your build system.

The [primary audience for this library is software engineers](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#not-bootstrap) with a build system in place so they can optimize for loading performance.

The eventual goal is to remove all lodash polyfills and use native features. You may consider polyfills for these features in the [core-js library](https://github.com/zloirock/core-js#commonjs) .

**Comment by interactivellama** [comment]
Closing now that https://github.com/salesforce/design-system-react/blob/master/docs/browser-compatibility.md exists.
