### ISSUE TITLE
React Warning from unguarded setState on modal

### ISSUE THREAD

**Issue by bzenSFDC** [salesforce/design-system-react#1225]
This needs to be cleaned up as it is showing up in our test suite.
https://github.com/salesforce/design-system-react/blob/master/components/modal/index.jsx

There is a React warning caused by:

```
		if (!this.state.revealed) {
			setTimeout(() => {
				this.setState({ revealed: true });
			});
```

We need to guard the setState with !isUnmounting in order to avoid the warning.

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Modal component.

**Comment by interactivellama** [comment]
I think what should be done is to use a `ref` function to trigger a state change and re-render with a different class, but I'm not sure. This is for the fade-in animation CSS. According to issue #296 from almost two years, the modal isn't even fading. Feel free to rip this out if you need to in the mean time if you can't figure out how to fix to not use timeouts. The fade is not currently working and that bug is open.
