### ISSUE TITLE
Question: Does webpack's tree-shaking work with babel-preset-design-system-react?

### ISSUE THREAD

**Issue by zaki-yama** [salesforce/design-system-react#1265]
I have a question.
In [Getting Started](https://react.lightningdesignsystem.com/getting-started/), it says

> This preset will keep Babel compatible with Design System React and allow ES6 module benefits such as tree-shaking.

but when I see the preset definition,
https://github.com/salesforce/design-system-react/blob/master/preset/index.js

`"modules": false` is not specified in babel-preset-env.
So I just wondered if ES6 modules features like tree-shaking really works using this preset. What do you think?

**Comment by interactivellama** [comment]
You are right. `modules` should be `false` for that. I believe I initially wrote the preset with `modules:false` but then left it out in order to ship it. `modules:false` was causing issues.

For instance, we still have some CommonJS to clean up like `module.exports = RadioGroup;`. Changing to ES6 modules would be a breaking change.

What would you recommend? I think we can turn it on once. If you can change the few modules and get Storybook and the tests going. I'll update the preset.

**Comment by zaki-yama** [comment]
@interactivellama 
I really appreciate for your reply.
I understand, and found there are some components which uses `module.exports = xxx` style.

>  I think we can turn it on once the CommonJS is gone.

I agree. I wish I could be your help for migrating the modules.
