### ISSUE TITLE
Update SLDS peer dependency to allow 2.6.0

### ISSUE THREAD

**Issue by garygong** [salesforce/design-system-react#1296]
I'd like to give SLDS v2.6.0-alpha a try, but our dependency range doesn't include prerelease tags.  Can we include it in our allowable range?

**Comment by interactivellama** [comment]
Do `npm install` warnings block your build process? I think we've tried to stick to beta versions in the past.

I don't have any engineering issues with adding it since I believe `npm install @salesforce-ux/design-system` will still pick a non-alpha by default, but I'm hesitant to change the version every time SLDS comes out with an alpha release. 

What do you think? Would allowing all minor releases work? `^2.4.0`. That seems like it would be better than `>=2.4.x` which allow `3.0.0` I believe.

**Comment by garygong** [comment]
Yeah, I see this error during `npm install`: 
```npm ERR! peerinvalid The package @salesforce-ux/design-system@2.6.0-alpha does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer design-system-react@0.8.7 wants @salesforce-ux/design-system@>=2.4.x
```

The React thread was informative.  I agree that `^` would be better than `>=`.  A possible solution could be that we use the pattern `^<current release> || ^<next release>-alpha`.  I don't anticipate that we would need to update this more than once a release.  What do you think?  I really don't feel _that_ strongly about using the next release.  So if we don't like that option, at least we should replace `>=` with `^`.

Also, I did a quick check and `npm install @salesforce-ux/design-system` does indeed install the non-prerelease version by default.
