### ISSUE TITLE
Can GlobalNavigationBarDropdown behave like navigation item?

### ISSUE THREAD

**Issue by tserkoniukv** [salesforce/design-system-react#1309]
Hi there!

There are example of slds Global Navigation:
https://lightningdesignsystem.com/components/global-navigation/

In this example we can see menu item with submenu dropdown, so we can navigate to this item as well as to submenu items. In react slds we have GlobalNavigationBarDropdown which have submenu with links but it is not behave like menu link.
![example](https://user-images.githubusercontent.com/36413765/38023004-ccd88d86-3289-11e8-84bc-09a276d11f1d.gif)

Is it possible to implement this behaviour using design-system-react?

**Comment by interactivellama** [comment]
I believe all the `MenuDropdown` props can be used by the `Dropdown` within GlobalNav folder. See https://react.lightningdesignsystem.com/components/dropdown-menus/#prop-openOn for hover effect. It's not shown in the example for GlobalNav because I believe there are some accessibility concerns with a hover-only implementation.

**Comment by vtserkoniuk** [comment]
Yes, you are right about hover. But the question is different. GlobalNavigationBarDropdown can contain a list of links, but can't behave like link itself.

For example, we want to create a Home navigation item, and we want its drop-down list to contain links to recent actions on the Home page or links to specific items on the Home page.

**Comment by interactivellama** [comment]
I don't think it has that since the whole component is a dropdown and not just the little arrow button. There may be an `onclick` prop of dropdown though https://github.com/salesforce/design-system-react/blob/master/components/menu-dropdown/menu-dropdown.jsx#L272

You might be able to use that for navigation, but that means that keyboard users will get navigated somewhere else when they try to open a menu which is a bad experience.

I'm open to the component being updating to limit the dropdown click / keyboard enter / open the menu action to the arrow and not the text. I think that's the latest pattern in SLDS.

**Comment by interactivellama** [comment]
I think this will be fixed with SLDS alignment task #1647.
