### ISSUE TITLE
Error  'Warning: Received `true` for a non-boolean attribute `focusable`

### ISSUE THREAD

**Issue by girishla** [salesforce/design-system-react#1352]
I get the following Error in the console when I use a DataTable. 
Version: 0.8.14

```
Warning: Received `true` for a non-boolean attribute `focusable`.

If you want to write it to the DOM, pass a string instead: focusable="true" or focusable={value.toString()}.
    in th (created by SLDSDataTableHeaderCell)
    in SLDSDataTableHeaderCell (created by SLDSDataTableHead)
    in tr (created by SLDSDataTableHead)
    in thead (created by SLDSDataTableHead)
    in SLDSDataTableHead (created by SLDSDataTable)
    in table (created by SLDSDataTable)
    in SLDSDataTable (created by JobsTable)
    in SLDSIconSettings (created by JobsTable)
    in div (created by JobsTable)
    in JobsTable (created by JobsListView)
    in SLDSIconSettings (created by JobsListView)
    in div (created by JobsListView)
    in JobsListView (created by ZincJobs)
    in ZincJobs (created by UserIsAuthenticated(ZincJobs))
    in UserIsAuthenticated(ZincJobs) (created by Connect(UserIsAuthenticated(ZincJobs)))
    in Connect(UserIsAuthenticated(ZincJobs)) (created by withSaga(Connect(UserIsAuthenticated(ZincJobs))))
    in withSaga(Connect(UserIsAuthenticated(ZincJobs))) (created by withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs)))))
    in withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs)))) (created by Connect(withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs))))))
    in Connect(withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs))))) (created by Route)
    in Route (created by RouteWithLayout)
    in div (created by PageBase)
    in div (created by PageBase)
    in div (created by PageBase)
    in div (created by PageBase)
    in PageBase (created by RouteWithLayout)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in MuiThemeProvider (created by Layout)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Route)
    in Route (created by withRouter(WithWidth))
    in withRouter(WithWidth) (created by Connect(withRouter(WithWidth)))
    in Connect(withRouter(WithWidth)) (created by RouteWithLayout)
    in RouteWithLayout (created by App)
    in Switch (created by App)
    in div (created by App)
    in Router (created by App)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App) (created by Connect(withRouter(App)))
    in Connect(withRouter(App))
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
```

**Comment by girishla** [comment]
Just noticed this could be a duplicate of #1329
That seems to have been included in the release 0.8.14 but I still seem to get the error.

**Comment by interactivellama** [comment]
A string makes sense: `focusable={sortable ? 'true' : 'false'}`

**Comment by girishla** [comment]
See React issue facebook/react#10521 for more info. 
It looks like this Warning was introduced in 16.x for attributes that rely on coercion if booleans are used.

**Comment by interactivellama** [comment]
@girishla Would you like to correct it or would you like me to add to the [Public Non-Feature Backlog](https://github.com/salesforce/design-system-react/milestone/20).

**Comment by girishla** [comment]
@interactivellama I would love to be able to contribute but I'm a Windows user - Unfortunately many of the scripts such as the one that bootstraps the tests are all shell scripts.

**Comment by interactivellama** [comment]
Anything we can do to help make Windows users a full participant in this library's community? Encapsulating our shell scripts in NodeJS, may be a good path forward. https://www.npmjs.com/package/shelljs

@dougwilson Do you have a suggestion for running bash commands in Windows for open source projects that will allow a larger community without much extra effort on the Windows users?

What is standard practice these days? This is [what we do now for tests](https://github.com/salesforce/design-system-react/blob/master/scripts/local-qa.sh)--although I'm open to simplifying it. All the conditionals are in there because these full test suite takes around 6 min to run due to ES6/webpack builds, etc. and some contributors wanted to optionally run some of the tests.

What we actually do without all the conditional logic CLI cruff:

```
npm run lint
karma start --single-run
npm run snapshot-test
npm run build-and-test-docs
```

**Comment by dougwilson** [comment]
So as a Windows dev for Node.js things, there are a few options you can do:

(1) Most Windows devs interacting with git repos have Git for Windows installed, which comes with bash. This gives them bash to run things already, though it's pretty slimmed down, so if you want that to be the answer, you'll want to try not to use an external programs (i.e. just bash internals as much as you can).

(2) Write scripts like this in node, so it just runs on the same platform they need anyway since this is a node project

(3) As an extension of num 2, you can use a node-based runner like gulp or grunt, etc.

That example script itself doesn't really seem very complicated, could probably use something like yargs and quickly convert it to a node script that works the same way the bash script already works there.

The commands it shells out are pretty simple, so you could probably just use `execSync` from node core itself vs pulling in shelljs if you don't want to.

If desired, I can volunteer to convert them to help out 👍 they would be the same, just in node.

**Comment by interactivellama** [comment]
Thank you for the offer! I've created https://github.com/salesforce/design-system-react/issues/1366 for you @dougwilson

**Comment by interactivellama** [comment]
@dennismphil This is a pretty easy one, too if @ivanbogdanov doesn't want it.

**Comment by Hugofv** [comment]
``` javascript
import React from 'react';
import { Button } from "@material-ui/core";
import styled from "styled-components";

export default styled(({ primary, margintop, ...other }) => <Button {...other} />)`
  background-color: ${props => (props.primary ? "#CC131D !important" : '#EAEAEA !important')};
  color: ${props => ((props.primary && !props.disabled && "#FFF !important") || (!props.primary && !props.disabled && "#CC131D !important") || (props.disabled && "#6C6C6C !important"))};
  outline: none !important;
`;
```
