### ISSUE TITLE
Update React Modal version

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1355]
I'm going to guess this is the oldest out-of-date code we have now that Tether is gone.

@garygong states that tests fail when updating to latest.

We are on v1. Last release is v3.4.4. This may require a rewrite of DSR Modal component--however all we do right now is wrap and render, so the component isn't that complex.

**Comment by interactivellama** [comment]
Please check if updating Modal version resolves. #963 and close if it does.

**Comment by futuremint** [comment]
If you're using React v16 and have wrapped your modal in another component, and that "outer" component unmounts, you'll get an exception from inside of Modal.js because of [this react-modal issue](https://github.com/reactjs/react-modal/issues/476).  Using react-modal v2.2.3 or newer appears to fix the issue (I'm currently just forcing a different version in my project's build phase).
