### ISSUE TITLE
Implement Field Level Help and Inline Help for Input

### ISSUE THREAD

**Issue by garygong** [salesforce/design-system-react#1474]
We'd like to implement the "Field level help" and "Inline help" variants for Input. The SLDS spec for those are here: https://latest-216.lightningdesignsystem.com/components/input/  

![screen shot 2018-07-26 at 11 06 49 am](https://user-images.githubusercontent.com/7608505/43279934-59c09ae8-90c4-11e8-96eb-7f2b70658019.png)
![screen shot 2018-07-26 at 11 06 54 am](https://user-images.githubusercontent.com/7608505/43279936-59da49ac-90c4-11e8-9836-9700bc23ed8a.png)

A few options to consider:
- Add `fieldLevelHelp` and `inlineHelp` props that, when specified, adds the help text next to the label.
- Add a `help` prop whose value is one of `fieldLevel`, `inline`.  This allows us to keep the help text in a single prop.  This also enforces that only one variant of the help text can be used at a time.
- Change the prop type of `label` so that it one of `string`, `node`, and allow the user to implement help text themselves.

I'm leaning towards the second option.  What do you think?

**Comment by interactivellama** [comment]
I think this will get a lot of cross cloud usage. (I've been wondering if folks are cramming it into the label prop right now 😉).

My gut says have a `fieldLevelHelpTooltip` that would pass in an entire `Tooltip` component due to alignment customization and [learn more variant usage](https://react.lightningdesignsystem.com/components/tooltips/) (4th example). What do you think about that implementation? Do you think it's too heavy? We could do both: "easy" _and_ "advanced" usage.

@kwilloughby Is next to a field label a frequent place to see a "Learn more" tooltip.

If it is, we probably want to pass in a tooltip with the [Component composition with prop spread](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#component-composition-with-prop-spread) method.

`inlineHelp` should probably be similar to `errorText` maybe `inlineHelpText`?

Since it's under examples. I don't think the two are required to NOT be used in the same field. One clarifies the label with additional information and one gives an example of the format. (kind of similar to the latin abbreviations e.g. and i.e.). Is there a statement somewhere that says don't use them both?

**Comment by garygong** [comment]
Yeah, I think that both Field Level Help and Inline Help variants can be used at the same time.  

You have a good point about passing in an entire `Tooltip` for Field Level Help.  Let's do that; and then have inlineHelpText for the Inline Help variant.
