### ISSUE TITLE
Date picker throw "Cannot read property 'getTimezoneOffset' of null" when date is null/invalid

### ISSUE THREAD

**Issue by jingwangsfdc** [salesforce/design-system-react#1494]
To reproduce the issue:
1. bring up date picker and select a date
2. while focus still in the date input field right after pick a date, tab on delete key

Cause:
handleInputChange (event) {
		this.setState({
			formattedValue: event.target.value,
			inputValue: event.target.value,
		});

		const date = this.props.parser(event.target.value);

		if (this.props.onChange) {
			this.props.onChange(event, {
				date,
				formattedDate: event.target.value,
				timezoneOffset: date.getTimezoneOffset(),
			});
		}
	}
date is null because it is an invalid value.

Related work item:
[removed]

I will fix this issue if it is valid.

@interactivellama

**Comment by garygong** [comment]
I would expect the custom `parser` to handle an invalid date value and still return a `Date` object, perhaps just a `Date()`?  What do you think?

**Comment by interactivellama** [comment]
Apologies for the delayed reply. If I select `8/14/2014` and then press delete. I get `8/14/201` which is a valid date. 201 A.D.

This is what I'm seeing:
<img width="443" alt="screen shot 2018-08-16 at 5 33 04 pm" src="https://user-images.githubusercontent.com/1290832/44240254-82f55b80-a17a-11e8-921a-cd1cddb15520.png">

As @garygong commented, this Datepicker should always be used with a custom `parser` prop.

From https://react.lightningdesignsystem.com/components/datepickers/#prop-parser
```
Custom function to parse date string into and return a Date object. Default function passes the input value to `Date()` and _prays for a miracle_. Use an external library such as [MomentJS](https://momentjs.com/) if additional date parsing is needed.
```

As product owner, I've been hesitant to add a dependency on MomentJS. In previous Datepicker components I've worked on in [previous design systems](http://getfuelux.com/), it has complicated things, and so with this library, I've tried to limit the scope to just the UI, but the built in `Date()` is for sure an awful parser.

@jingwangsfdc I would recommend _always_ using a custom `parser` prop. One thing we could do is fire off a console warning if no custom parser if provided, so that no one has to go hunt it down on the doc website.

I've created #1507, but it's not a fix--it's a notification for others like yourself to recommend not using the default parser.

**Comment by interactivellama** [comment]
@jingwangsfdc After some thought, one thing that would be helpful to all consumers is if you could add MomentJS as a dev dependency and get it working as a custom parser in the default example of Datepicker in Storybook. That way others could copy and paste it out in the future. 

https://github.com/salesforce/design-system-react/blob/master/components/date-picker/__examples__/default.jsx

**Comment by jingwangsfdc** [comment]
@interactivellama Thanks for your suggestion. We currently using aura localization service parser and passed it in to date picker, however it not able to parse 8/14/201 into a valid date. We plan to enhancing our current date picker to allowing manual input in 218, will definitely considering adding the custom parser as you suggested.

**Comment by interactivellama** [comment]
@jingwangsfdc I'm going to close this issue. Feel to free to re-open for continued discussion or any related matter. 💯
