### ISSUE TITLE
Cleanup component section in package.json

### ISSUE THREAD

**Issue by davidlygagnon** [salesforce/design-system-react#1522]
In #1503, we are now defining component documentation at the component level. Each component now has a `docs.json` file that contains documentation pertinent to the component.

In this issue, once [Design System React Site issue](https://github.com/salesforce-ux/design-system-react-site/issues/112) is resolved, we need to do the following: 

1. Cleanup the component section from package.json
2. Refactor `build-docs.js` script to reference docs.json files instead of the component section in `package.json`.

**Comment by interactivellama** [comment]
BrandBand is the only net new component between these two tasks.

**Comment by interactivellama** [comment]
@kevinparkerson I propose we:

* Auto-update the `package.json` array based on a search for `components/**/docs.json` similar to how `component-docs.json` works today. This would mean that new component contributors would only need to have the `docs.json` present in the component folder to get "on the website."
* We we would then convert the components section of `package.json` to an array of file paths to docs.json. This would be similar to how `site-stories.js` works today.
* We should probably tackle #1165 at the same time since we will be in the site code together then.
