### ISSUE TITLE
Add 'required' Boolean Prop to DatePicker

### ISSUE THREAD

**Issue by ctrimm** [salesforce/design-system-react#1524]
After looking thru the docs and source code, it appears that the `<DatePicker>` component does not have a `required` boolean.

Mostly all other components have support for this - `<Input>`, `<TimePicker>`, `<Checkbox>`, `<Combobox>`, etc...

After reading thru the previous closed issues in this repo, it appears that `<SLDSSingleDatepicker>` [had this option at one point in time](https://github.com/salesforce/design-system-react/pull/242/files).

**Comment by interactivellama** [comment]
It was removed, so that we don't add one component's props to another component and have API creep. Composition is preferred now.

You can do that here. https://github.com/salesforce/design-system-react/blob/master/components/date-picker/date-picker.jsx#L564

![screen shot 2018-08-31 at 3 43 33 pm](https://user-images.githubusercontent.com/1290832/44937054-a6043b80-ad34-11e8-93cd-1f36b57187bc.png)

I agree it's not very obvious that children is for an `Input` to be passed in. More recent components have a render prop instead of making the render prop implicitly children. Hopefully, I'm a better component prop designer today with the introduction of the more explicit render prop than I was two years ago. 😞 

If you'd like to contribute a deprecation of the `children` prop via `checkProps` and add a more obvious `input` with [Component composition with prop spread](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#component-composition-with-prop-spread), I'd appreciate it.
