### ISSUE TITLE
Remove <title> elements from included Illustrations.

### ISSUE THREAD

**Issue by jgerigmeyer** [salesforce/design-system-react#1639]
I've been having quite a bit of trouble figuring out how to use `Illustration` components properly. Because the SLDS illustrations (https://lightningdesignsystem.com/components/illustration/) rely on CSS class styles, it seems they can't really be included with a `path`. But the `illustration` requires converting to a custom SVG object, which isn't ideal.

So it seems the best options are either to convert one of the SLDS illustrations so that it has inline styles instead of relying on CSS, or to just use one of the three illustrations included in design-system-react. Or, of course, just bypassing the `Illustration` component entirely and using an inline SVG.

The three included illustrations, however, have `<title>` elements which cause tooltips on mouseover, and can't be overridden. I'll submit a PR to remove those elements, and clarify the Illustration docs a bit.

**Comment by interactivellama** [comment]
Yeah, title isn't needed.

To be transparent, SLDS only has the illustrations in a usable way on the website via copy and paste and I believe those have to be slightly modified. It is not a high priority for SLDS to include the illustrations in a usable way within the public NPM module.

Therefore, I introduced bringing illustration files into DSR, so that all the consumers of DSR can use them in a scaleable way, and any updates to the Illustration can scale across DSR consuming applications (update once!) and not be a static copy and paste image that never is updated once pasted into an application. I'll look at your pull request
