### ISSUE TITLE
Add Carousel Component

### ISSUE THREAD

**Issue by PaulaIoana** [salesforce/design-system-react#1697]
Would like to implement the \<Carousel\/\> component in React.
(https://www.lightningdesignsystem.com/components/carousel/)

Proposed props:
<pre>
Carousel.propTypes = {
	/**
	 * Array of objects with shape, needed for building a carousel item.
	 * A shape would have:
	 *   - id: 0   [REQUIRED]
	 *   - heading: "All my things! Part 0" // (Visible heading for default render)
	 *   - description: "Card 0 description."
	 *          // (Visible paragraph text for default render and navigation bullet text used in
	 *              assistive text tag)   [REQUIRED]
	 *   - imageAssistiveText: "First card accessible description."
	 *          // (image alt text, OPTIONAL, required if `src` is present),
	 *   - href: "https://www.salesforce.com" // (OPTIONAL, void(0) if not provided for default template
	 *   - src: "/images/examples/carousel-01.png"
	 */
	items: PropTypes.array.isRequired,
	/**
	 * Number of items to be displayed at a time in the carousel
	 */
	itemsPerPanel: PropTypes.number,
	/**
	 * Boolean showing whether the autoplay feature is available or not (by showing the autoplay 
         * button or not)
	 */
	hasAutoplay: PropTypes.bool,
	/**
	 * Interval for the autoplay iteration
	 */
	autoplayInterval: PropTypes.number,
	/**
	 * Boolean for displaying the navigation indicators left/right arrows) of the carousel
	 */
	hasPreviousNextPanelNavigation: PropTypes.bool,
	/**
	 * Boolean for infinite loop navigation
	 */
	isInfinite: PropTypes.bool,
	/**
	 * CSS classes that are applied to the component
	 */
	className: PropTypes.oneOfType([
		PropTypes.array,
		PropTypes.object,
		PropTypes.string,
	]),
	/**
	 * CSS style that is applied to carousel indicators
	 */
	indicatorStyles: PropTypes.object,
	/**
	 * Id of component, if desired. If not provided an id is automatically generated
	 */
	id: PropTypes.string,
        /**
	 * Accepts a custom carousel item rendering function
	 */
	onRenderItem: PropTypes.func,
	/**
	 * Description of the menu for screen-readers.
	 */
	assistiveText: PropTypes.shapeOf,
};

Carousel.defaultProps = {
	itemsPerPanel: 1,
	hasAutoplay: false,
	hasPreviousNextPanelNavigation: false,
	isInfinite: false,
        assistiveText: {
		nextPanel: 'Next Panel',
		previousPanel: 'Previous Panel',
	},
};
</pre>

**Comment by PaulaIoana** [comment]
Updated some the proposed props as per your comments.

**Comment by interactivellama** [comment]
Dustin reached out to me and gave me the visual design, so I understand the multiple items per panel need and am happy to support it.

* The default number of items per panel should be 1, so that the default one tab panel one item wrapped in a link from the SLDS site can occur without custom rendering.
* Multiple items within a panel should add an additional unordered list `ul`/`li` of things that just look like panels, but aren't tab panels semantically, and the content/custom render provided by `onRenderItem` should go within those `li` tags.
* The default value for `hasNavigation` should be false, due to the SLDS base template not having them and [No truthy defaults for boolean type props](https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#no-truthy-defaults-for-boolean-type-props) guideline. Since there are two navigation elements in this proposal, `hasNavigation` should be more specific and something like `hasPreviousNextPanelNavigation`.
* Please approach this component as a unique [Tabs](https://www.lightningdesignsystem.com/components/tabs/) component. I think there are more guidelines on the Tabs component that might be helpful if you haven't looked over that page.
* To support multiple items in a tab panel, the assistive text in the bottom navigation should be an unordered list within the bottom navigation. It's just a string for the default template since the default template is one item per panel.

```
    <a id="indicator-id-01" class="slds-carousel__indicator-action
     slds-is-active" href="javascript:void(0);" role="tab" 
     tabindex="0" aria-selected="true" aria-controls="content-id-00-01-02" // Here is where you will need an id for each panel. For multiple item panels, you can concatenate the item ids.
     title="Visit App Exchange tab">
    <div className="slds-assistive-text>
        <ul> // here is where the component will need structured data for the description of a panel
            <li>Card 0 description.</li>
            <li>Card 1 description.</li>
            <li>Card 2 description.</li>
        </ul>
    </div>
</a>
```

Due to this component needing to be accessible and rendering the same text in multiple locations, we will need a little more structured data than an array of React elements rendered. You can see that with `id="indicator-id-02"` and aria-controls="content-id-02"  on the SLDS site's code. Custom rendering content should be an override and not a default expectation for consuming developers. This also means if new slide templates are added in the future, then we can support them with a provided variant straight out of the box.

For that reason, here is some psuedo-code that has a good pattern.
```
const items = [{
        id: 0, // REQUIRED
        heading: "All my things! Part 0", // (Visible heading for default render)
        description: "Card 0 description.", // (Visible paragraph text for default render and navigation bullet text used in assistive text tag)   [REQUIRED]
        imageAssistiveText: "First card accessible description.", // (image alt text, OPTIONAL, required if `src` is present),
        href: "https://www.salesforce.com", // (OPTIONAL, void(0) if not provided for default template
        src: "/images/examples/carousel-01.png"
    },
    // ...
];

const handleRenderItem = ({ id, heading, description }) => (<div className="slds-heading">{items[id].heading}</div>);

<Carousel 
    items={items}
    onRenderItem={handleRenderItem}
/>
```

What do you think of this pattern?

**Comment by PaulaIoana** [comment]
As long as there is a way of adding a custom layout for the carousel if there is ever needed one, that's great.
I updated the props with your suggestions.

**Comment by interactivellama** [comment]
You'll have complete control with `onRenderItem`/`handleRenderItem`. You can do whatever you want based on the `id`.

**Comment by djmccormick** [comment]
@interactivellama / @PaulaIoana -- is this proposal approved at this point?

**Comment by interactivellama** [comment]
Yes, looks good!

**Comment by interactivellama** [comment]
@kevinparkerson Here is the example currently in Platform on the Home screen.

![carousel](https://user-images.githubusercontent.com/1290832/56303789-f7154400-60f9-11e9-996a-a4e4d0128c24.png)
