### ISSUE TITLE
Add Chat Component

### ISSUE THREAD

**Issue by aswinshenoy** [salesforce/design-system-react#1872]
Implement the Chat component according to spec: https://www.lightningdesignsystem.com/components/chat/

**Comment by aswinshenoy** [comment]
Here is my initial prop proposal for the component, what do you think?

### Chat
| Name | Type | Description |
|---|---|---|
| ClassName | array/object/string | Additional Class Names |
| isPastChat | boolean | Whether the chat is from past. Defaults to false. |
| children | Element[ ] | Chat body/content |

### Message
| Name | Type | Description |
|---|---|---|
|direction|enum {"inbound","outbound"}| Direction of the message|
|time|string| Time of sending message |
|user|string| User sending the message |
|showAvatar|boolean| Whether to show user avatar. Defaults to false. |
|isTyping|boolean| Whether user is typing the message. Defaults to false. |
|peek|boolean| Whether to peek into message being typed. Defaults to false. |
|isUnsupported|boolean| Whether the message is unsupported. Defaults to false.|
|isUndelivered|boolean| Whether the message is undelivered. Defaults to false.|
|isCurrentAgent|boolean| Whether the message is sent by current agent. Defaults to true.|

### Attachment
| Name | Type | Description |
|---|---|---|
|direction|enum {"inbound","outbound"}| Direction of the message|
|time|string| Time of sending message |
|user|string| User sending the message |
|thumbnail|string| URL to thumbnail |
|link|string| Link to the attachment |
|title|string|  Title for the attachment |
|format|string| Format of the attachment|

### Event
| Name | Type | Description |
|---|---|---|
|time|string| Time of the event |
|title|node| Description of the event |
|icon|string| Icon for the event |
|message|string| Message left by the agent additionally |
|isError|boolean| Whether the event is an error. Defaults to false.|


Here is a basic example using these specs -

```jsx
<Chat>
    <Event
      title={<span>Chat started by<b>Andy Martinez</b></span>}
      time="4:58 PM"
      icon="chat"
    />
    <Message
        direction="inbound"
	    time="4:59 PM" 
		user="Andy Martinez"
		showAvatar
	>Hi, my CloudWidget only speaks French</Message>
	<Message
        direction="outbound"
	    time="5:02 PM" 
		user="Jason Dewar"
	>Hi Andy, thank you for contacting Widget Support. Can you please tell me what language you are trying to program on your CloudWidget?</Message>
	<Attachment
	    thumbnail="...."
	    title="Image.jpg"
	    format="image"
	    link="..."
	 />
</Chat>
```

**Comment by interactivellama** [comment]
Great props proposal. It's clear for a complex component.

* `isUnsupported` and `isUndelivered` should probably be the same prop, since they can't both be true and it looks like they are limited to whether they are inbound or outbound.
* `peek` and `showAvatar` are booleans and probably should be `isSneakPeek` and `hasAvatar`
* Attachment should be a variant of the `File` component https://www.lightningdesignsystem.com/components/files/ 's "File with actions" it could be named Attachment, but take all the same props of `File`. I see that you proposed making File https://github.com/salesforce/design-system-react/issues/1879 so that's good. You might consider making that one first after the API is approved. So I am going to wait to comment on the props until file is reviewed.
* `title` should probably be reserved for the HTML `title` attribute. `label` is fine.
* Event should probably have variants that choose the icon.
* Many of the `string` types should also be `node` also, so that styling can be done on the text.
* I see `showAvatar` but I don't see an an `avatar` prop. Maybe it should just the avatar if one is passed in?

Please update and confirm by posting to this thread.

**Comment by interactivellama** [comment]
I will try to get https://github.com/salesforce/design-system-react/issues/1879 looked over tomorrow.
