### ISSUE TITLE
Grid component

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce/design-system-react#2020]
Do we need Grid component
https://www.lightningdesignsystem.com/utilities/grid/#site-main-content
or its better to use with divs and classNames

**Comment by interactivellama** [comment]
I'm open to adding it if you want to make a props proposal and then work on it once approved. The reason it's not in here, is that I am biased toward working on the let's say "more complicated" components like `form` elements such as `input` or ones that have ARIA specs such as `Tree` and `TreeGrid` in order to make sure we get those right instead of making layout components that designers can "red-line" and ask their product engineers to fix if wrong. That's my take on it.

### A little background
A grid component exists at https://github.com/salesforce/design-system-react/blob/master/components/grid/index.jsx that has not been updated from 2016, but I don't even know what it gives us. It's purposely not on the documentation site. I'm open to deprecating the current component and starting from scratch if you'd like to proceed.
