### ISSUE TITLE
Left icon and fixed left text overlap in SLDS Input

### ISSUE THREAD

**Issue by FeiZhan** [salesforce/design-system-react#2074]
In SLDS Input component, if we set both ```iconLeft``` and ```fixedTextLeft```, they overlap. I reproduced this bug by modifying ```components/input/__docs__/storybook-stories.jsx``` (see screenshot). It is reproducible in 42052a266f0b254eed41617c4a9d4fc7f2d8caf2 in master branch. This bug blocks my user story in Salesforce.
![image1](https://user-images.githubusercontent.com/1351474/59713196-b1d9c500-91c3-11e9-8d6d-82d250b2bb71.png)

**Comment by interactivellama** [comment]
I'm not sure that use case is supported by SLDS CSS, since there is no example of it. https://www.lightningdesignsystem.com/components/input/

I would suggest following up with SLDS to see if it's a pattern for the design system. Have you investigated what the workaround would like like. I think those icons are absolutely positioned, so it'd probably be a CSS override.

**Comment by FeiZhan** [comment]
Got feedback from Salesforce internal. Thanks.
