### ISSUE TITLE
ButtonGroup variant "list" throws error/does not show "label"

### ISSUE THREAD

**Issue by DerekJacobi** [salesforce/design-system-react#2153]
When using the `list` variant for the ButtonGroup component:

```
<ButtonGroup
    labels={{ label: 'Font Style' }}
    variant="list" >
```
The following error is thrown:

`Failed prop type: Invalid prop "variant" of value "list" supplied to "SLDSButtonGroup", expected one of ["checkbox"].`

The `label` passed into the `labels` prop also does not show, unless the variant is `checkbox`. It does not show with the `list`, or an empty variant.

https://react.lightningdesignsystem.com/components/button-groups/#prop-labels

**Comment by DerekJacobi** [comment]
@interactivellama Heres the issue we discussed yesterday

**Comment by pulkonet** [comment]
@DerekJacobi  Are you on the latest version of DSR? Because the `list` variant is working fine for me. About the labels though, `label` and `error` aren't currently working, but I also don't find any such example on SLDS website that supports labels with `list`. Can you please explain what the actual requirement is so that it becomes easier to add it?

**Comment by interactivellama** [comment]
@DerekJacobi What kind of component are you using for children? Checkboxes, Radios, Buttons?

Typically labels are needed only for form elements (that is types of `input` tags). Typically, Button Groups that use form items are checkboxes or radio since that implies selection. Button Groups that contain just buttons don’t need a `label` tag to be accessible, however this sounds like a design decision. That is the design spec calls for a label on a ButtonGroup that contains Buttons as children. Is that correct?

**Comment by interactivellama** [comment]
@pulkonet I think this is the design Derek is implementing and he wants button styled checkboxes in a button group. 

![Screen Shot 2019-07-10 at 9 17 02 AM](https://user-images.githubusercontent.com/1290832/60981427-8f832500-a2f3-11e9-871f-85ad9554da8c.png)

@DerekJacobi Are you wrapping the “checkbox buttons” in Tooltip and therefore need to use a ButtonGroup list variant?

**Comment by pulkonet** [comment]
In this design, I don't think an `error` label is required, or is there a case where it can be required?

**Comment by interactivellama** [comment]
@kevinparkerson We should stick with the label styling provided by SLDS and allow for CSS override.

If it has label, add fieldset wrapper and allow `classNameContainer`
