### ISSUE TITLE
Combobox: Limit required attribute on Input to variants that give input a value

### ISSUE THREAD

**Issue by davidakerr** [salesforce/design-system-react#2154]
https://codesandbox.io/s/practical-mestorf-ffkkq?fontsize=14

When required is set to true HTML 5 Validation stops user from being able to proceed if they do not type to search but instead select options with mouse.

Please advise.

**Comment by interactivellama** [comment]
Auto-complete Comboboxes shouldn't be disabled or required (at least as far as the input goes, since there nothing in the input. 

I'd be open to allowing the visual required "red dot" and removing the required attribute from the input if you'd like to contribute it. This UX pattern change should be limited to variants that have no value in the input. For a similar pattern, see the `singleInputDisabled` prop
