### ISSUE TITLE
Add onRenderPageType Prop to BuilderHeader component

### ISSUE THREAD

**Issue by arshana** [salesforce/design-system-react#2242]
Hi @interactivellama I'm on @garygong's team and wanted to make an addition to the BuilderHeader component. I want to make pageType in the BuilderHeader component optionally a string or another component. Currently it can only be a string. I want to make pageType customizable by the user. So I’ll make a new pageType component with an onRenderPageType function. I’ll also add a new example with the component option to BuilderHeader.

What do you think?

**Comment by interactivellama** [comment]
@arshana Welcome to the project. Looking forward to collaborating!

There's not a need for `onRender` callbacks for labels typically. Visible labels should take `PropTypes.oneOfType([PropTypes.node, PropTypes.string]),` in order to support formatting `spans`, italic, bold, etc.

Does that work for you all?

Please review the DOM structure. Are you wanting something outside the `h1` tag? If that is true, we may want to change the `children` prop or something else.

**Comment by arshana** [comment]
Yes, we want to completely replace the `h1` element with something else.  

Do you mean adding something like a `BuilderHeaderCustomItem` child component, like this:

```
<BuilderHeader>
	<BuilderHeaderNav>
		<BuilderHeaderCustomItem>
			Custom content here
		</BuilderHeaderCustomItem>
	</BuilderHeaderNav>
</BuilderHeader>
```

This could also work.  What do you think?

**Comment by interactivellama** [comment]
Props should be semantic. If it's not having to do with page type, I'd recommend using another mechanism.

When I look at the component https://www.lightningdesignsystem.com/components/builder-header/#Variations , you've got the name section, the nav section, and the utilities section.

You are wanting to add stuff to the flexbox middle `<div class="slds-builder-header__item slds-has-flexi-truncate"></div>`

I'm not sure it has a name, but something like this. It's a region just like `BuilderHeaderNav`.
```
<BuilderHeader>
	<BuilderHeaderNav>
	</BuilderHeaderNav>
	<BuilderHeaderCustomItem>
		Custom content here
	</BuilderHeaderCustomItem>
</BuilderHeader>
```

**Comment by interactivellama** [comment]
If it's navigation, it needs to go inside the existing `nav` tag. I'm not quite sure what else would go up there. If it's not navigation, we need to come up with another name. GlobalNavigationBar has Primary and Secondary.

**Comment by arshana** [comment]
That makes sense. We don't want to add anything inside the nav. What you posted is correct.

**Comment by interactivellama** [comment]
Maybe `<BuilderHeaderMiscellaneous />` would be good?

**Comment by garygong** [comment]
A third option could be that it could be a child of `<BuilderHeader>`, like this:
```
<BuilderHeader>
	<BuilderHeaderNav />
	Custom content here
</BuilderHeader>
```
If that section doesn't have a name, maybe we're thinking too hard trying to name it.

**Comment by arshana** [comment]
For the new component, I'm thinking of reusing code from SLDSInlineEdit prop, but edited to use https://www.lightningdesignsystem.com/components/form-element/#Inline-Edit. Is that okay? Or else I can try writing the component with just https://www.lightningdesignsystem.com/components/form-element/#Inline-Edit...

**Comment by interactivellama** [comment]
If it's a single input and not say a 10 input form in a Modal. SLDS recommends and Edit Dialog (mostly due to accessibility) for editing in-place text.

http://design-system-react-components.herokuapp.com/?path=/story/sldspopover--edit-dialog

**Comment by interactivellama** [comment]
SLDSInlineEdit is old pattern from 3 years ago and should not be used. It's inaccessible for one thing.

**Comment by interactivellama** [comment]
@garygong I'm OK with just adding children since, if you don't have `nav` it looks like this:

<img width="641" alt="Screen Shot 2019-08-23 at 10 38 07 PM" src="https://user-images.githubusercontent.com/1290832/63632609-de142680-c5f6-11e9-8da2-afae930d917a.png">

My one concern is the logic that grabs the children that are not nav or toolbar--would you build an array of left over children?
