### ISSUE TITLE
Map component crashes all site examples

### ISSUE THREAD

**Issue by kevinparkerson** [salesforce/design-system-react#2347]
Need to figure out how to get it to play nicely with CodeMirror

**Comment by interactivellama** [comment]
@nik72619c Yes, if I had to guess it's an iframe issue since it works in Storybook. http://design-system-react-components.herokuapp.com/?path=/story/sldsmap--multi-locations

I thinking the best option would be to add an `onRenderMap` and pass in the location or whatever else is needed to replace the `iframe`, so that someone could use a different service (Apple Maps, etc?) if they wanted to.

```
<Map onRenderMap={{
  ({ location: 'text'}) => <iframe><html><body><div>Maps preview disabled for location: {location}</div><body/></iframe>
```

If you can figure out how to get the current Google Maps iframe working in Code Mirror that'd be great, too!

**Comment by kevinparkerson** [comment]
@nik72619c have you already started on this? We're a little unsure about the best solution for this one, if you haven't begun working on it I will probably be taking this up as there is a bit of conversation @interactivellama and I will need to have to decide on the right direction

**Comment by nik72619c** [comment]
Cool :)
