### ISSUE TITLE
[A11y] Toast: Focus is placed on the close button and not the link

### ISSUE THREAD

**Issue by stamizharasu** [salesforce/design-system-react#2372]
- When a toast with a link is presented to the user, the focus is placed on the button to close out the toast. The user is then not able to tab immediately to the link -- pressing tab moves them to other components on the page.

 

![Screen Shot 2019-10-10 at 11 15 33 AM](https://user-images.githubusercontent.com/47190423/66595191-51460d80-eb4f-11e9-8e08-36b633ddc6d6.png)

* I am not currently working on this issue
* To reproduce, place the toast with a link in your page and attempt to tab and place focus on the link text.
* Story created - [W-5986014](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006RsMIIA0/view)

**Comment by interactivellama** [comment]
@stamizharasu As a workaround, can you auto focus the link on render or does the close button focus grab back again from the link?

I'm not sure what the best way is to focus on dynamic content is, since LDSR doesn't know anything about your link or which DOM node it is.

One way forward, may be to allow disabling of LDSR controlling the focus and you grabbing the focus on render of your link. Do you think that would work for you?

**Comment by shaundr** [comment]
@interactivellama thank you for following up!

> can you auto focus the link on render
I'm not positive what you mean by this -- on render callback use a DOM selector to focus the link?

**Comment by interactivellama** [comment]
I mean `<a ref={(c) => c.focus();}>ACME-100<a> `--although I think @kevinparkerson tried this in a recent meeting and said the focus goes to the close button again.

Adding a `hasNoAutoFocus` may be the best route if you can't do the line of code above.

**Comment by interactivellama** [comment]
There is update on this one. We moved back to focusing on the container of the Toast, so that all the text of it's contents is read.
