### ISSUE TITLE
Audit components: event callbacks should pass syntheticEvent, then customData object

### ISSUE THREAD

**Issue by donnieberg** [salesforce/design-system-react#273]
Suggestion from @tweettypography 

Make all custom event callbacks have two properties `handleEvent(customData, syntheticEvent)`. The first prop would be an object with whatever is being passed back from the app - updated values, etc - and the second is simply the original triggering event. 

TO DOS
- Change all components to this pattern
- Update docs

**Comment by interactivellama** [comment]
Update. I will write console warnings for these events and break them at a later date.

**Comment by interactivellama** [comment]
Console warning won't do much good, because everyone is going to call `onChange` on a checkbox or an input, so you will have a warning, but you can't make a backwards compatible version, because it's event parameters you are passing out, not props you are taking in.

Proposal:
* I'm still going through the components, but so far checkbox and inlineInput's `onChange` event are the primary events that need updating.
* My proposal is to move the form component out of the forms folder. This will allow me to keep a backwards compatible version of the component in the old location, but allow anyone going forward to use the new location which will have different parameters passed out of the event callback. The old one will be aliased to the new with a prop flag `oldOnChangeEventParaters: true` so that there's no code duplication, and this will flip the callback into compatibility mode with the old API.
* This is the only way I think of that can make it backwards compatible, this will also allow me to know whether the developer is using the new or old API.

@futuremint What do you think?
