### ISSUE TITLE
DataTable: onRenderSubHeadingRow de-select all does not de-select all rows

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2738]
When using `onRenderSubHeadingRow`, these rows are selectable which causes "Select All" checkbox to be indeterminate when all rows are selected and not uncheck all rows when clicked.

https://user-images.githubusercontent.com/1290832/104245791-2289a780-5422-11eb-8253-74c6d79acdcf.mp4

**Comment by bxiao** [comment]
In the `data-table` component, when non-selectable items (as shown in the above video) are present in the `items` array, the `selection` array (which only includes selectable items) would never match `items`, which results in an `indeterminate` state for the SelectAll checkbox when all (selectable) items are selected in the table. This is also the root cause for the issue that unchecking the SelectAll checkbox doesn't clear all the selections.

In the `data-table` component, there is currently no way to check whether an `item` in the `items` array is selectable. I propose we add an (optional) `boolean` property `isSelectable` to the `item` object:
```
items: PropTypes.arrayOf(
	PropTypes.shape({
		id: PropTypes.string.isRequired,
		classNameRow: PropTypes.string,
                isSelectable: PropTypes.boolean,
	})
).isRequired,
```

We can then use this new property to correctly determine the state of the SelectAll checkbox.
