### ISSUE TITLE
Modal Jumps to 50% of Page Height

### ISSUE THREAD

**Issue by scott-joe** [salesforce/design-system-react#963]
Modals scroll the page down to 50% of entire page height instead of simply filling the viewport.

![2017-04-11 12 39 41](https://cloud.githubusercontent.com/assets/2026866/24932389/57bebc64-1edf-11e7-9e15-e13fe260cf10.gif)

See conversation https://salesforceux.slack.com/archives/C122U6T4P/p1491938319415621

**Comment by shaundr** [comment]
QA on Trailhead has picked up on this as well.

**Comment by shaundr** [comment]
This appears to be related to https://github.com/reactjs/react-modal/issues/585

**Comment by interactivellama** [comment]
```
<style>
.ReactModalPortal {
    position: fixed;
    top: 0;
}
</style>
```
is a temporary fix until https://github.com/salesforce/design-system-react/blob/66712ef9061b91c281901a1bc7747443e97305ac/components/modal/index.jsx#L399 can be changed. Although `portalClassName` should be able to do this and would be preferred over `style`--but this is "JS only" library... If we add a style then that will have more CSS specificity than `portalClassName`.

The best solution looks like changing the `customStyles` to be `fixed/top` as above _and_ adding a `portalStyle` prop in order to allow it being overridden, since we don't want to promote `!important` usage in external CSS.

**Comment by davidlygagnon** [comment]
@scott-joe I'm working on upgrading react-modal. Do you perhaps have a codepen to share to repro the modal jump ? I created a minimal example with react-modal version 1.7.7 but I don't see the jump down.

**Comment by interactivellama** [comment]
@davidlygagnon Check out the modals moving the background page on the doc website https://react.lightningdesignsystem.com/components/modals/

**Comment by davidlygagnon** [comment]
I've been looking into this and I'm now able to create a [CodePen](https://codepen.io/dlygagnon/pen/wjmmPr?editors=1111) to illustrate the issue.

When opening the modal, it jumps to the bottom of the page ( difference with the issue here is that it's jumping at 50% of the page...)

It seems to be related to the style prop that we pass to `<ReactModal>` in DSR code, that is,  
```
const customStyles = {
    content: {
        ...
    },
    overlay: {
        position: 'static', // set this to absolute and the modal won't jump
        backgroundColor: 'default',
    },
};
```

If I change the position of the overlay to absolute, the modal doesn't jump anymore.
Note that I'm using ReactModal version 3.4.4, so I don't think it's related to ReactModal.

@interactivellama Do you remember why are setting the overlay position to static ?

**Comment by interactivellama** [comment]
It was to fix this bug. #200 It appears that we can remove it if absolute position items still appear "behind" the overlay.

**Comment by davidlygagnon** [comment]
Ah yes - removing `position` (well, setting it back to react-modal default prop: `position=fixed`) will actually break #200 .

<img width="1420" alt="screen shot 2018-05-18 at 4 53 25 pm" src="https://user-images.githubusercontent.com/1821787/40262450-3bdd2002-5abc-11e8-8788-f4378a46805b.png">

I think what I can do here is to set the proper z-index on the overlay so that we can remove `position=static`. Currently the `z-index` on the overlay is 0, which is a little strange. That way, both issues will be fixed and no one has to introduce any new code. 

@interactivellama What do you think ?

**Comment by interactivellama** [comment]
[SLDS site](https://www.lightningdesignsystem.com/design-tokens/#category-z-index) says that's modal is z-index of 9000 and overlay is 8000. We should follow those guidelines.

**Comment by davidlygagnon** [comment]
Cool - I'll set it to 8000.
